# Generated by Django 3.0 on 2019-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial_appdata_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genius_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(null=True, related_name='playlists', to='app.Song'),
        ),
    ]
