# Generated by Django 3.0 on 2019-12-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_many_to_many_and_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='playlists_followed', to='app.UserProfile'),
        ),
        migrations.DeleteModel(
            name='PlaylistFollow',
        ),
    ]
