# Generated by Django 3.0 on 2019-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_new_relationships_no_temp_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
