# Generated by Django 3.0 on 2019-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_title_for_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
