# Generated by Django 3.0 on 2019-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_charfield_for_playlist_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.ManyToManyField(related_name='playlists_followed', to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', to='app.Song'),
        ),
    ]
