# Generated by Django 3.0 on 2019-12-20 17:17

import app.models.song
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_no_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genius_artist_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genius_infos',
            field=app.models.song.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genius_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
