# Generated by Django 3.0 on 2019-12-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_new_structure_for_songs_genius_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, default='nBgMrpc74KKcRReIadLugClgPpck7zKj', max_length=32, null=True),
        ),
    ]
