# Generated by Django 3.0 on 2019-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_added_playlist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, default='Q2Z6ArWWxwKtsioPuyjR6wdd639D8SBV', max_length=32, null=True),
        ),
    ]
