# Generated by Django 3.0 on 2019-12-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_added_slug_field_for_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, default='CWx7piWLaONVBqjOTMb8aOKRVY5Q9zu6', max_length=32, null=True),
        ),
    ]
