# Generated by Django 3.0 on 2020-01-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_unique_slug_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, default='YHraq4wTGcz5zjxCLHI47lca1POta23Q', max_length=32, null=True),
        ),
    ]
