# Generated by Django 3.0 on 2020-01-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_new_jsonfield_for_genius_api_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, default='uqIV0mIkKRwQ4ArBQeQgKt6pqdgIfd92', max_length=32, null=True),
        ),
    ]
