# Generated by Django 3.0 on 2020-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_back_to_text_field_on_genius_data_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.CharField(blank=True, default='Y77gAodsERbrY8dRfuuXkHTn5hCQUSiq', max_length=32, null=True),
        ),
    ]
